### ISSUE TITLE
Extra CSP tuning needed?

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/birdbox#273]
On future.m.o we have CSP enabled with reporting, which lets us see which things get blocked. You can see [here](https://mozilla.sentry.io/issues/?project=4505953315913728&query=is%3Aunresolved&referrer=sidebar&statsPeriod=90d) what kind of thing has been happening - some of it is extensions, some of it people playing about with the page I think, and a few entries which do actually look like we might need to add them to the allowlist so that we don't break our (anonymised) analytics.

The current CSP (with linebreaks for convenience) is
```font-src 'self'; 
connect-src 'self' https://region1.google-analytics.com https://basket.mozilla.org www.google-analytics.com; 
frame-src 'self' www.youtube-nocookie.com www.youtube.com player.vimeo.com; 
child-src 'self'; 
default-src 'self'; 
style-src 'self' 'unsafe-inline'; 
object-src 'none'; 
base-uri 'none'; 
script-src 'self' www.googletagmanager.com; 
media-src 'self'; 
img-src 'self' data: https://storage.googleapis.com/future-prod-prod-storage/ https://region1.google-analytics.com https://www.googletagmanager.com; 
report-uri https://o1069899.ingest.sentry.io/api/4505953315913728/security/?sentry_key=a75fce86fc6ac9f0c0ae6ca378e5c14e
```

This Issue is to work out which of the following, if any, need allowing, and if there are others lurking in the report that we need to allow. 

- [ ] `connect-src analytics.google.com` Blocked 'connect' from 'analytics.google.com' [link](https://mozilla.sentry.io/issues/4792470224/?project=4505953315913728&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=10)
- [ ] `script-src-elem www.google-analytics.com`Blocked 'script' from 'www.google-analytics.com' [link](https://mozilla.sentry.io/issues/4737443513/?project=4505953315913728&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=13) - note that www.google-analyics.com is in `connect-src` but not `script-src`
- [ ] `img-src www.google-analytics.com` Blocked 'image' from 'www.google-analytics.com' [link](https://mozilla.sentry.io/issues/4687175433/?project=4505953315913728&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=17)
- [ ] `script-src-elem www.googletagmanager.com` Blocked 'script' from 'www.googletagmanager.com' [link](https://mozilla.sentry.io/issues/4698669470/?project=4505953315913728&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=20)
- [ ] `script-src-elem ssl.google-analytics.com` Blocked 'script' from 'ssl.google-analytics.com - [link](https://mozilla.sentry.io/issues/4746192911/?project=4505953315913728&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=16) - maybe we should just allow `*.google-analytics.com`?
- [ ] I'm also wondering why this was blocked as an `img-src`, when the CSP config appears to allow it [link](https://mozilla.sentry.io/issues/4720084426/?project=4505953315913728&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=2)

We should also bear in mind that this CSP policy is very very similar to what we have on www.m.o - so if it needs to be more permissive here to allow the anonmymised analytics, www.m.o may need the same tweaks

**Comment by stevejalim** [comment]
@stephaniehobson When you're around - really no rush - would you be able to talk through this with me, please, given your stronger experience of CSP than mine?

**Comment by stephaniehobson** [comment]
This is the best guidance I found from Google on this: [Google Tags > Security & Privacy](https://developers.google.com/tag-platform/security/guides/csp#google_analytics_4_google_analytics ). 

```
script-src:  https://*.googletagmanager.com
img-src:     https://*.google-analytics.com https://*.googletagmanager.com
connect-src: https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com
```

So your impulse to allow `*.google-analytics.com` is a good one.

`script-src-elem` is a more specific version of `script-src` -- we can leave it out and browsers should fall back to `script-src` or you can copy the values of `script-src` to remove the error message from the logs ;)

**Comment by stephaniehobson** [comment]
Also, I can't see the Sentry links so I'm not sure about the `img-src` violation that was last on the list.

**Comment by stevejalim** [comment]
Thanks @stephaniehobson! I'll update the CSP list now, and I've also given you access to the Sentry reports for futuremo-prod

**Comment by stephaniehobson** [comment]
I don't know why that image was blocked and I couldn't replicate it 🤷‍♀️
