### ISSUE TITLE
[Epic] Add requested pages for innovations site

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/birdbox#32]
Based on https://www.figma.com/file/NUNAO6zA36wmDlTvgCHcj3/birdbox-thumbnails-innovations?type=design&node-id=0-1&mode=design&t=GoQIOm2getMhbfl5-0, we need to provide the six page types shown

### Current live pages

- [x] https://github.com/mozmeao/birdbox/issues/46
- [x]  https://github.com/mozmeao/birdbox/issues/47
- [x]  https://github.com/mozmeao/birdbox/issues/48

### From Elise

- [x]  https://github.com/mozmeao/birdbox/issues/50
- [X] Blog (Done already)
- [x] https://github.com/mozmeao/birdbox/issues/51
- [x]  https://github.com/mozmeao/birdbox/issues/52
- [x] https://github.com/mozmeao/birdbox/issues/53

## Non-MVP:

- [ ]  https://github.com/mozmeao/birdbox/issues/49

**Comment by stevejalim** [comment]
@craigcook @slightlyoffbeat I put this list together based on the current MEICO site and what Elise had in Figma.

**Comment by stevejalim** [comment]
Closing as an epic - there's only straggling page which can happen post-MVP
