### ISSUE TITLE
Support animated GIFs

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/birdbox#457]
By default, Wagtail does not support animated GIFs, but it can be enabled https://docs.wagtail.org/en/v5.2.6/advanced_topics/images/animated_gifs.html and it's needed by the Innovations team

## Tasks

- [ ] Add support for animated GIFs locall
- [ ] Check running on birdbox demo
- [ ] release to futuremo
- [ ] Update documentation
